### ISSUE TITLE
[FEAT] Making the site feel more interactive with hover effects and a little animation

### ISSUE THREAD

**Issue by marsian83** [Codezilla-Club/website#10]
## Feature Description
The buttons and cards on the site feel a little static, we could make them feel a bit more interactive if we add hover effects to the cards and the buttons.

**Summary:**
Add animations and hover effects

## Proposed Method
CSS hover pseduo selectors, action pseudo selectors and animations using keyframes

## Additional context
we could have the cards grow in size and have a slight glow when hovered upon, same for the buttons maybe just with the slight glow.

- [x] I want to work on this

**Comment by marsian83** [comment]
If this is an enhancement which could be considered. Can I be assigned to this under hacktoberfest?

**Comment by Akshu-on-github** [comment]
Hey there @marsian83!
That sounds amazing, I'll assign this Issue to you

**Comment by marsian83** [comment]
#11 implements this @Akshu-on-github

**Comment by Akshu-on-github** [comment]
@marsian83 - requested two changes to maintain code consistency but on the whole, we're good to go!

**Comment by Akshu-on-github** [comment]
Thanks for contributing! ✨
I'll close this Issue now
