### ISSUE TITLE
[DOC] Update list of team members

### ISSUE THREAD

**Issue by Akshu-on-github** [Codezilla-Club/website#12]
## Feature Description

**Summary:**
Update the list of team members along with the links to their GitHub avatars in `home/index.html`

**Screenshots:**
For now, we have the following placeholder

![image](https://user-images.githubusercontent.com/61582763/194545502-f3f9dbd0-319c-4b62-8abc-73c51070e5d5.png)

## Proposed Method

**Summary:**
Add the following code snippet for each team member under the [Team Section](https://github.com/orgs/Codezilla-Club/people)

```html
<div class="team-icons">
  <a href="https://github.com/<username>">
    <img src="<gh-profile-photo>" alt="<name>"/>
  </a>
  .
  .
  .
</div>
```

- [ ] I want to work on this

**Comment by animeshk923** [comment]
Hello there @Akshu-on-github !

I would like to work on this issue. Please guide me through this and I'll do it.
Thank you!

**Comment by RohitShah1706** [comment]
Hey there @Akshu-on-github 
I have decent experience with frontend.
I would like to fix this issue. Please assign this issue to me.

**Comment by samikshakute** [comment]
Hey @Akshu-on-github 
I would like to contribute! Please guide me through this.

**Comment by sukalyanbisui** [comment]
i want to work on this.

**Comment by Akshu-on-github** [comment]
@AnimeshKumar923, I'll assign this issue to you, good luck!

@RohitShah1706 @samikshakute @sukalyanbisui the issues are assigned first come first serve - but do keep an eye out, we'll be updating the issues soon after we add our event page!

**Comment by animeshk923** [comment]
@Akshu-on-github Thanks for assigning me but I am seeing that @lakshmipriya166 has already made a PR #13 
Requested to review that and take that forward as I'm confused in proceeding with this issue.
Thank you!

**Comment by Akshu-on-github** [comment]
@AnimeshKumar923 - I'm afraid that that PR is invalid as it does not follow the contributing guidelines

I'll assign @RohitShah1706 to this Issue

**Comment by animeshk923** [comment]
@Akshu-on-github I'm confused as how to add the logos/circle profile pictures. Tried this https://github.com/AnimeshKumar923/codezilla-club-website but you can see the result.
Please guide me through this. Haven't learned about html,css,js right now...

**Comment by lakshmipriya166** [comment]
Hi...
Sorry for the confusion... I'm contributing for the first time and so didn't know the guidelines... 
I'll adhere to the guidelines henceforth...
Thanksss :)

**Comment by Akshu-on-github** [comment]
@lakshmipriya166 - no worries, we all make mistakes. Since it is your first PR, I'll merge it, but please go through the CONTRIBUTING.md of a project before raising an Issue/PR next time

@AnimeshKumar923 - I'm afraid that you've made changes to the wrong file. But hey, it happens to the best of us - do contribute next time

**Comment by animeshk923** [comment]
@Akshu-on-github Thank you for your time!

**Comment by lakshmipriya166** [comment]
Thank you soooo much @Akshu-on-github
