### ISSUE TITLE
[BUG]  Instagram logo is not visible

### ISSUE THREAD

**Issue by Anish-Parkhi** [Codezilla-Club/website#14]
## Problem Description

**Summary**
The Instagram logo at the bottom left corner is not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/93964690/194689511-88839aab-badf-4458-b3c6-7a445d2c70c5.png)

**Device**
This bug is visible on all devices

**Comment by lakshmipriya166** [comment]
the instagram logo is visible

![Screenshot 2022-10-08 112056](https://user-images.githubusercontent.com/61225829/194691349-f322cba7-eaf4-44da-af19-a8bd8107be20.jpg)

**Comment by Akshu-on-github** [comment]
This bug is not reproducible on my devices as well. I'll close this issue now
