### ISSUE TITLE
[FEAT] README.md update/improvization

### ISSUE THREAD

**Issue by tmsagarofficial** [Codezilla-Club/website#20]
## Feature Description

**Summary:** I would like to point out that at this stage the README.md of this repo is very small and has very less interactables and missing of other stats. And i feel the favicon of this website can be updated to make the website look better.

**Screenshots:** 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/110724849/195103211-c12b8349-7cca-4178-ad67-56a343bb917f.png">

## Proposed Method

**Summary:** I would like to suggest work on this to add some more interactables like direct links to the site some basic features explaination and also changing the favicon to something new like it can be the firefox logo used in the letter "O" of the CODEZILLA name. i think it would great if we could something like a viewer and  star counter with other small banners like made with love by students of SRM

## Additional context

- [x] I want to work on this

**Comment by Akshu-on-github** [comment]
We're keeping the favicon on hold for now, but please feel free to improve the README.md - may I have a summary of what changes that you're planning on?

**Comment by tmsagarofficial** [comment]
@Akshu-on-github  Hi again, Thanks for reaching back .
i am planning for the following changes.
- To add visitor/star count and it looks like this when added 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/110724849/195230304-752b20be-3ba1-43b0-a487-1b722f978ecc.png">
- I can make this page look more cooler with this kind of badges 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/110724849/195230402-0eead4b7-40a1-4d5a-ad2c-f2b03f8383a2.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/110724849/195231005-d666e5e6-2e24-42d8-8481-36ebf9ea03f5.png">

- I think adding images/snapshots of the site can help
- A link to the website on the title would help very much.
- We could also list the techstack used like
<img width="298" alt="image" src="https://user-images.githubusercontent.com/110724849/195230900-d07c895c-7aca-481d-8028-22867e1942fa.png">
- And making a few changes at the end of readme.md to make it inclusive and welcoming like
<img width="244" alt="image" src="https://user-images.githubusercontent.com/110724849/195231249-6d1b9dd1-c7b7-4358-a7cf-19769c9da470.png">

**Comment by tmsagarofficial** [comment]
And will try and see what else can be added to make it shine ✨

**Comment by Akshu-on-github** [comment]
Looks amazing, sounds amazing - go for it! Maybe drop the viewcounter alone, as it can be artificially increased by refreshing the page

**Comment by tmsagarofficial** [comment]
@Akshu-on-github Hi again, Thanks for assigning it to me. Will surely solve this ASAP .

**Comment by tmsagarofficial** [comment]
Should i msg u any other platform to get some input about the community so that can also be updated in the readme?? @Akshu-on-github

**Comment by tmsagarofficial** [comment]
@Akshu-on-github PLs check

**Comment by Akshu-on-github** [comment]
The new readme looks awesome @tmsagarofficial - thanks again for contributing, I'll close this issue for now!

**Comment by tmsagarofficial** [comment]
Pls add haktoberfest-accepted label 😅

**Comment by Akshu-on-github** [comment]
Oops, thanks for reminding me! Added the same 👍
