### ISSUE TITLE
[BUG] Broken 404 Page

### ISSUE THREAD

**Issue by Akshu-on-github** [Codezilla-Club/website#7]
## Problem Description

**Summary**
The 404 Not Found page is broken

**To Reproduce**
Steps to reproduce the behaviour:
1. Open browser
2. Open the link `https://codezilla-club.github.io/website/home/404.html`

**Screenshots**
| Expected Behaviour | Actual Behaviour |
|-|-|
| ![image](https://user-images.githubusercontent.com/61582763/193605350-26b8d26a-e75a-4f50-ad67-8332b31f862d.png) | ![image](https://user-images.githubusercontent.com/61582763/193605641-fa0f4e92-f41c-4653-a8c3-22540d8fefeb.png) |

**Device**
The devices with observed behaviour:
- Mobile (Android)
- Laptop (Chrome, Mozilla)

**Comment by Akshu-on-github** [comment]
On review, the reason for this is that the yaml data added according to the [GitHub docs for custom 404 page](https://docs.github.com/en/enterprise-server@3.4/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) - it was supposed to be only for `404.md` files and not `404.html` files. Thus, please complete the following tasks
- [ ] Remove the following code from the `404.html` page
    ```yaml
    ---
    permalink: /404.html
    ---
    ```
- [ ] Update the navigation links (refer to the `home/index.html` file for the correct links)

**Comment by Stevecmd** [comment]
> On review, the reason for this is that the yaml data added according to the [GitHub docs for custom 404 page](https://docs.github.com/en/enterprise-server@3.4/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) - it was supposed to be only for `404.md` files and not `404.html` files. Thus, please complete the following tasks
> 
> * [x]  Remove the following code from the `404.html` page
>   ```yaml
>   ---
>   permalink: /404.html
>   ---
>   ```
> * [x]  Update the navigation links (refer to the `home/index.html` file for the correct links)

Could this task be assigned to me?

**Comment by Akshu-on-github** [comment]
Sure thing, best of luck @Stevecmd!

**Comment by Stevecmd** [comment]
> Sure thing, best of luck @Stevecmd!

Thanks!

**Comment by Stevecmd** [comment]
Hi @Akshu-on-github I have completed the tasks, however, I performed them as two different pull requests, I hope this does not cause any issues. I would love some feedback, looking forward to hearing from you. Thanks.

**Comment by Akshu-on-github** [comment]
I see that you've merged your PRs to your main branch - I think it should be fine if you create another PR for the main branch of this repo

**Comment by Stevecmd** [comment]
Oh, thanks for the feedback I'll look into it.

**Comment by Stevecmd** [comment]
Hi, I tried the PR again, is it on the correct branch this time?

**Comment by Akshu-on-github** [comment]
@Stevecmd - are you still working on this issue?

**Comment by Stevecmd** [comment]
Hi @Akshu-on-github I have created a new pull request, I hope it works this time, I am not sure why its fine on my end but not proper on the main branch.

**Comment by Stevecmd** [comment]
Additionally, I did update two links which will be shown on the pull request, vector.css and menu.css, if it was unnecessary I believe its possible not to allow the change. Thank you for your patience.

**Comment by Akshu-on-github** [comment]
Hey there!

>Hi @Akshu-on-github I have created a new pull request, I hope it works this time, I am not sure why its fine on my end but not proper on the main branch.

Ah, that's alright - the source branch doesn't make as much of a difference as the destination branch but no worries. I'll update the tags on the PRs asap

>Additionally, I did update two links which will be shown on the pull request, vector.css and menu.css, if it was unnecessary I believe its possible not to allow the change. Thank you for your patience.

I'm afraid the wrong links were changed here, as pointed out in this [CR](https://github.com/Codezilla-Club/website/pull/8#discussion_r987774782). But no worries - as requested, I've cherry-picked the relevant commits. This does, however, make both PRs redundent

**To ensure that your contribution is eligible for hacktoberfest, I'm going to:**
- Add the `duplicate` and `invalid` labels to PR #8
- Add the `hacktoberfest-accepted` label to PR #9 
- Keep PR #9 open till the end of the wait period (one week from now)
